site_name: MiniML documentation

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: cyan

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
      accent: cyan
      default: true

nav:
  - Home: index.md
  - setup.md
  - start.md
  - save_load.md

plugins:
- search
- autorefs
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    locale: en
    handlers:
      python:
        paths: [./src]
        options:
          show_root_heading: true
          show_symbol_type_heading: true
          show_source: false
          members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences