# This workflow will install Python dependencies, and run tests with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare-data:
    name: Prepare DVC data
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.8.11"
    - name: Install dependencies
      run: |
        uv sync
    - name: Pull DVC data
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        uv run task pull-data
    - name: Upload DVC data artifact
      uses: actions/upload-artifact@v4
      with:
        name: dvc-data
        path: tests/test_nn/data

  build:
    name: Run tests (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: prepare-data
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Download DVC data artifact
      uses: actions/download-artifact@v4
      with:
        name: dvc-data
        path: .
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install UV
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.8.11"
    - name: Install dependencies
      run: |
        uv sync
    - name: Test with pytest
      run: |
        uv run task test